#Chemins vers les executables
medit         = "medit "
mmgs          = "mmgs_O3 "
mmg3d         = "mmg3d_O3 "
tetgen        = "tetgen "
mshdist       = "mshdist "
python        = "python3 "
blender       = "/home/lydieuro/Bureau/FaciLe-DataRecons/blender/blender "
meshlabserver = "LC_ALL=C meshlabserver "
wrapping      = "/home/lydieuro/Bureau/FaciLe-DataRecons/testSourceWarping/build/warping "
morphing      = "morphing "
elasticity    = "elastic "
EVERYTHING    = "/home/lydieuro/Desktop/FaciLe-DataRecons/DATA/mesh "
