#Chemins vers les executables
medit         = "medit "
mmgs          = "mmgs_O3 "
mmg3d         = "mmg3d_O3 "
tetgen        = "tetgen "
mshdist       = "/home/loic/bin/mshdist "
python        = "python3 "
blender       = "blender "
meshlabserver = "LC_ALL=C meshlabserver "
wrapping      = "/home/loic/Development/Warping/build/warping "
morphing      = "/home/loic/Development/Morphing/build/morphing "
elasticity    = "/home/loic/Development/LinearElasticity/build/elastic "
EVERYTHING    = "/home/loic/FACILE/EVERYTHINGELSE"
